# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.0"

gem "sqlite3", "~> 1.4"

gem "activerecord", "~> 6.0", :require => "active_record"

gem "rake", "~> 13.0"

gem "sinatra-activerecord", "~> 2.0"

gem "require_all", "~> 3.0"

gem "pry", "~> 0.13.1"

gem "shotgun", "~> 0.9.2"
