source "https://rubygems.org"

gem "rack", "~> 2.2"

gem "sinatra", "~> 2.0"

gem "require_all", "~> 3.0"

gem "sinatra-activerecord", "~> 2.0"

gem "activerecord", "~> 6.1"

gem "pry", "~> 0.13.1"

gem "shotgun", "~> 0.9.2"

gem "sqlite3", "~> 1.4"
